### ISSUE TITLE
Hide mouse in drawing area

### ISSUE THREAD

**Issue by Esshahn** [nurpax/petmate#113] opened 2018-09-04 09:17 UTC
The mouse pointer is always on top of the character in drawing mode, making it impossible to see. I'd recommend to try just hiding the mouse in the drawing area as we have the cursor indicating the position already. I'm positive this will work out just fine. What do you guys think?

**Comment by nurpax** [comment] 2018-09-04 09:51
Closing as a duplicate of https://github.com/nurpax/petmate/issues/56

**Closed by nurpax** 2018-09-04 09:51 UTC
Labels: duplicate
